const Constants = {
  AUTH_TOKEN_NAME: "AUTH_TOKEN",
  REFRESH_TOKEN_NAME: "REFRESH_TOKEN",
  API_VERSION: "v1",
  TIMEOUT: 5000,
  HEADERS: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
  
  ERROR_MESSAGES: {
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Forbidden access",
    NOT_FOUND: "Resource not found",
    SERVER_ERROR: "Internal server error",
    TIMEOUT: "Request timed out",
    BAD_REQUEST: "Bad request",
    UNEXPECTED_ERROR: "An unexpected error occurred",
  },
  SUCCESS_MESSAGES: {
    LOGIN_SUCCESS: "Login successful",
    LOGOUT_SUCCESS: "Logout successful",
    REGISTRATION_SUCCESS: "Registration successful",
    PASSWORD_RESET_EMAIL_SENT: "Password reset email sent",
    PROFILE_UPDATE_SUCCESS: "Profile updated successfully",
    ITEM_ADDED_SUCCESS: "Item added successfully",
    ITEM_UPDATED_SUCCESS: "Item updated successfully",
    ITEM_DELETED_SUCCESS: "Item deleted successfully",
    ITEM_FETCHED_SUCCESS: "Item fetched successfully",
    ITEMS_FETCHED_SUCCESS: "Items fetched successfully",
    ITEM_NOT_FOUND: "Item not found",
    ITEMS_NOT_FOUND: "Items not found",
    NO_INTERNET_CONNECTION: "No internet connection",
    NETWORK_ERROR: "Network error",
    SERVER_UNAVAILABLE: "Server unavailable",
    INVALID_CREDENTIALS: "Invalid credentials",
    TOKEN_EXPIRED: "Token expired",
    TOKEN_INVALID: "Token invalid",
    TOKEN_REFRESHED: "Token refreshed successfully",
    TOKEN_REFRESH_FAILED: "Token refresh failed",
    PASSWORD_CHANGED_SUCCESS: "Password changed successfully",
    PASSWORD_CHANGE_FAILED: "Password change failed",
    EMAIL_VERIFIED_SUCCESS: "Email verified successfully",
    EMAIL_VERIFICATION_FAILED: "Email verification failed",
    EMAIL_ALREADY_VERIFIED: "Email already verified",
    EMAIL_NOT_VERIFIED: "Email not verified",
    EMAIL_VERIFICATION_LINK_SENT: "Email verification link sent",
    EMAIL_VERIFICATION_LINK_FAILED: "Email verification link failed",
    EMAIL_NOT_REGISTERED: "Email not registered",
    EMAIL_REGISTERED: "Email already registered",
    USERNAME_TAKEN: "Username already taken",
    USERNAME_AVAILABLE: "Username available",
    USERNAME_NOT_FOUND: "Username not found",
    USERNAME_FOUND: "Username found",
    USERNAME_INVALID: "Invalid username",
    USERNAME_VALID: "Valid username",
    PASSWORD_WEAK: "Weak password",
    PASSWORD_STRONG: "Strong password",
    PASSWORD_MISMATCH: "Passwords do not match",
    PASSWORD_RESET_LINK_SENT: "Password reset link sent",
    PASSWORD_RESET_LINK_FAILED: "Password reset link failed",
    PASSWORD_RESET_SUCCESS: "Password reset successfully",
    PASSWORD_RESET_FAILED: "Password reset failed",
    ACCOUNT_LOCKED: "Account locked",
    ACCOUNT_UNLOCKED: "Account unlocked",
    ACCOUNT_DELETED: "Account deleted",
    ACCOUNT_NOT_FOUND: "Account not found",
    ACCOUNT_FOUND: "Account found",
    ACCOUNT_CREATED: "Account created successfully",
    ACCOUNT_CREATION_FAILED: "Account creation failed",
    ACCOUNT_UPDATED: "Account updated successfully",
    ACCOUNT_UPDATE_FAILED: "Account update failed",
    ACCOUNT_VERIFIED: "Account verified successfully",
    ACCOUNT_VERIFICATION_FAILED: "Account verification failed",
    ACCOUNT_VERIFICATION_PENDING: "Account verification pending",
    ACCOUNT_VERIFICATION_SUCCESS: "Account verification successful",
  },
};

export default Constants;
